### ISSUE TITLE
맥에서 install_pkg.sh 실행 시 오류 발생

### ISSUE THREAD

**Issue by nwaistd** [VeranosTech/vopt.conda#34]
맥의 디폴트 터미널이 bash 3.2 버전인 관계로 -v 연산자를 지원하지 않고 104 번째 줄에서 binary operator expected 에러를 발생시킵니다.

install_lib.sh에서 맥일 경우 bash를 업데이트 시키거나 별도로 문서를 만들어서 수동으로 업데이트할 수 있도록
안내해야 될 것 같습니다.

참고한 페이지입니다. 
https://apple.stackexchange.com/questions/193411/update-bash-to-version-4-0-on-osx
https://www.codeprocess.io/set-mac-terminal-shell-with-proper-GNU-bash-version-v4/
https://gist.github.com/Rican7/44081a9806595704fa7b289c32fcd62c

**Comment by joelkim** [comment]
확인 감사합니다. commit b140870b883825639bb54a7da783a8cce87f3fb7 에서 README 변경하였습니다.
