### ISSUE TITLE
windows에서 python3.6과 cvxopt가 충돌합니다.

### ISSUE THREAD

**Issue by Munki-Chung** [VeranosTech/vopt.conda#36]
create_env.bat 에서 python 3.6을 설치하면 install_pkg.bat에서 설치할 cvxopt와 충돌하여 common anaconda pakages부분이 설치되지 않고 넘어갑니다.

**Comment by joelkim** [comment]
실행한 명령어들과 순서, 그리고 출력되는 에러메세지를 복사하여 여기에 올려주세요. 
보다 자세한 내용이 있어야지 판단할 수 있습니다.

**Comment by Munki-Chung** [comment]
create_env.bat에서 python3.6을 설치한 후 install_pkg.bat을 실행하면
다음과같은 에러가 발생하고 conda-forge package설치로 넘어갑니다.

```
"Common Anaconda Packages:"


UnsatisfiableError: The following specifications were found to be in conflict:
  - cvxopt -> python 3.5*
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.

"Common Anaconda Packages in Conda-Forge:"
```

**Comment by joelkim** [comment]
네, 감사합니다.
찾아보니 다음과 같은 이슈가 있습니다.
https://github.com/cvxopt/cvxopt/issues/94
빠른 시일내에 고쳐질 것 같지 않습니다.
회의 때 이야기한 대로 Windows 지원을 중단하는 방향으로 생각해 보겠습니다.
