### ISSUE TITLE
install_pkg.sh 실행시 다음 경고가 발생

### ISSUE THREAD

**Issue by joelkim** [VeranosTech/vopt.conda#49]
```
python-xbrl 1.1.1 requires ordereddict, which is not installed.
python-xbrl 1.1.1 requires pep8, which is not installed.
distributed 1.21.8 requires msgpack, which is not installed.
boto3 1.7.19 has requirement botocore<1.11.0,>=1.10.19, but you'll have botocore 1.10.18 which is incompatible.
```

**Comment by nwaistd** [comment]
수정한 제 레포로 가상환경 빌드 시 아래와 같은 코드가 발생됩니다.
python-xbrl 1.1.1 requires ordereddict, which is not installed.
bdateutil 0.1 has requirement python-dateutil==2.2, but you'll have python-dateutil 2.7.2 which is incompatible.
awscli 1.15.19 has requirement colorama<=0.3.7,>=0.2.5, but you'll have colorama 0.3.9 which is incompatible.

ordereddict 패키지는 파이썬 2.x 만 지원하기 때문에 설치를 할 수 없고 
bdateutil는 python-dateutil을 다운그레이드 하면 aws 패키지 하나와 다시 충돌이 일어나기 때문에 의존성 이슈를 해결하기는 어렵습니다.
다만 bdateutil과 충돌이 나도 제 스파이더에서 사용할 때 이상은 없기 때문에 크게 문제 될 일은 없을 것 같습니다. 
또한 aws 패키지 간에 botocore 또는 colorama의 마이크로 버전 때문에 충돌이 일어나는데  
awscli==1.15.18, boto3==1.7.18로 다운그레이드 후 aws 패키지 사이에서 일어나는 충돌은 없앨 수 있었습니다.

**Comment by joelkim** [comment]
최신 버전으로 다시 에러가 발생하는지 확인해 주세요.

**Comment by nwaistd** [comment]
#48의 마지막 커밋으로 의존성 이슈를 해결했습니다.
가장 최신 버전으로 설치 시 파이썬3에서 해결 불가능한 ordereddict 패키지를 제외하면 의존성 이슈가 더 이상 없습니다.
