### ISSUE TITLE
vopt.conda/install_pkg.sh 실행 시 CyLP 오류

### ISSUE THREAD

**Issue by jhk104** [VeranosTech/vopt.conda#52]
```
CyLP package installing...
-bash: install_pkg.sh: line 145: conditional binary operator expected
-bash: install_pkg.sh: line 145: syntax error near `CYLP_SRC_DIR'
-bash: install_pkg.sh: line 145: `if [[ -v CYLP_SRC_DIR ]]; then'
```

**Comment by joelkim** [comment]
다음 명령으로 bash 버전을 좀 확인해 주세요.
```
echo $BASH_VERSION 
```

**Comment by jhk104** [comment]
3.2.57(1)-release

Bash 4.2 이상이 필요한게 맞나요? 업그레이드 했었는데 다시 확인해보겠습니다.

**Comment by joelkim** [comment]
Mac OSX의 기본 설치 bash 버전이 낮아서 생기는 문제입니다. 다음 링크를 참조하여 업그레이드 하세요.

https://apple.stackexchange.com/questions/193411/update-bash-to-version-4-0-on-osx

**Comment by joelkim** [comment]
README 문서에 내용을 추가하였습니다.
https://github.com/VeranosTech/vopt.conda/blob/master/README.md#bash-version-problem

**Comment by jhk104** [comment]
문제는 발견하였는데 해결 방법은 찾지 못했습니다. 아래와 같이 $BASH_VERSION은 $PATH를 수정하여도 바뀌지 않는 것 같습니다.

`JHKs-MacBook-Pro:~ jhk$ bash --version
GNU bash, version 4.4.23(1)-release (x86_64-apple-darwin17.5.0)
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
JHKs-MacBook-Pro:~ jhk$ echo $BASH_VERSION
3.2.57(1)-release
JHKs-MacBook-Pro:~ jhk$ 
JHKs-MacBook-Pro:~ jhk$ 
JHKs-MacBook-Pro:~ jhk$ echo $PATH
/usr/local/bin:/Users/jhk/anaconda3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin`

**Comment by jhk104** [comment]
아래 자료에 작성해주신 순서대로 실행하여 문제를 해결했습니다. 감사합니다.
https://github.com/VeranosTech/vopt.conda/blob/master/README.md#bash-version-problem
